### ISSUE TITLE
Identify on-premise encoder connections and state

### ISSUE THREAD

**Issue by JimTharioAmazon** [awslabs/aws-media-services-application-mapper#60]
Use the SSM agent connection to identify the current state of a on-premise encoder (online, offline, running, idle) and the connectivity between running jobs and the outside world.

**Comment by SteveWardAmazon** [comment]
Part of this would be including log entries, metrics and alerts from the on-premises equipment.

**Comment by JimTharioAmazon** [comment]
Redfish API for systems status
IDRAC enterprise provides Redfish API
Status of hardware

**Comment by estatt01** [comment]
Can this feature be implemented using SNMP traps to drive CWE instead of, or in addition to SSM? Reason is that log reaction time is much slower than SNMP.

**Comment by JimTharioAmazon** [comment]
Need to define a set of countable metrics (# tasks, errored tasks, complete, global status, on/off, etc.)
Use SSM to send the commands to encoders periodically for metrics
Use a SNS topic and Lambda to receive notification of command completed (needs to be created by the template at install)
Look up the command output in CloudWatch logs
Parse the countable metrics from the log data
Push metric values to CloudWatch metrics
Need to come up with calculable metric paths for encoders based on name, IP, etc.

**Comment by morjoan** [comment]
Instead of using an SNS topic, we are using a CloudWatch event rule to capture SSM completed commands. 

SSM command outputs are written in the MSAM/SSMRunCommand log group. 

Metrics are written to a custom namespace called MSAM/SSMRunCommand by Instance IDs. The following metrics are published: MSAMElementalLiveCompletedEvents, MSAMElementalLiveErroredEvents, MSAMElementalLiveRunningEvents, MSAMElementalLiveStatus (is the Elemental encoder process running), MSAMElementalLiveActiveAlerts, MSAMSsmSystemStatus (is the encoder up/reachable at all).
